development:
  adapter: postgresql
  encoding: unicode
  database: schedulemenow_development
  pool: 5
  username: aarontrostle
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: schedulemenow_test
  pool: 5
  username: aarontrostle
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: schedulemenow_production
  pool: 5
  username: aarontrostle
  password:
