# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Interview.create([
  { :interview_at => "2013-06-10 09:15:00", :notes => nil, :created_at => "2013-05-31 04:50:25", :updated_at => "2013-05-31 04:50:25", :instructor_id => nil, :applicant_id => nil },
  { :interview_at => "2013-06-10 09:30:00", :notes => nil, :created_at => "2013-05-31 04:50:25", :updated_at => "2013-05-31 04:50:25", :instructor_id => nil, :applicant_id => nil }
], :without_protection => true )

instructor_user = User.create(:email => "instructor@codefellows.com",
                              :password => "buttercup",
                              :instructor => true)

applicant_user = User.create(:email => "applicant@gmail.com",
                              :password => "buttercup")

